### ISSUE TITLE
Massive Lag when Movement History Enabled

### ISSUE THREAD

**Issue by JamzTheMan** [velara/pf2edragruler#11]
If I enable Movement History in Drag Ruler,  It can take 5-30+ seconds before token moves. It seems to happen more after the 4th+ drag.

Testing this with only the following modules active:

![image](https://user-images.githubusercontent.com/8051654/116443606-7bd2e680-a819-11eb-8f51-b2e3d756b7ea.png)

**Comment by velara** [comment]
I can't replicate this on my end. Sounds like something that could plausibly happen though if your server has less resources. Movement history is resource intensive and I had to add another layer on top of it to track completed actions. 

I'll see if there is any performance optimization I can do. But as far I can see there there isn't any bug that should be causing the lag you're experiencing.

**Comment by manuelVo** [comment]
I've just released Drag Ruler 1.6.0, which brings lots of performance improvements. Please verify whether this issue persists with that Drag Ruler version installed.

**Comment by velara** [comment]
I finally managed to replicate it with long enough paths thanks to manuelVo. 

With the changes to Drag Ruler in 1.6.1 and a more efficient movement speed pulling function with the latest version I'm seeing much better performance even for tokens with 20+ drags over paths of a couple hundred squares.
