### ISSUE TITLE
Paralyzed Problem 

### ISSUE THREAD

**Issue by Cosmic-Lattee** [velara/pf2edragruler#16]
When a creature has the paralyzed condition placed on them and it is later removed the color of their movement line remains red. The only way to get rid of it as far as I can tell is just to remake the character.

Edit: It happened again with a token being grabbed so it seems to be triggered by the immobilized condition (which makes sense , after it it is what is setting your speed to 0).

**Comment by velara** [comment]
I found the issue, there is a bit of orphaned code that was part of the big action tracking update. 
I should be able to fix this soon-ish. (Dev time is very limited). 

In the mean time you can fix the problem for any affected actors by entering into the console
game.actors.get(" **** ").unsetFlag('pf2e', 'actions') where you replace **** with the actor id.   And then reload. 

Apologies for the inconvenience.

**Comment by Cosmic-Lattee** [comment]
Thank you! Worked perfectly. <3

**Comment by velara** [comment]
Bug should be fixed in 0.4.7
