### ISSUE TITLE
Broken configuration can persist after uninstall

### ISSUE THREAD

**Issue by pizza-wizard** [velara/pf2edragruler#17]
It is possible to break the compatibility in certain environments and not other, identical environments. My uneducated hypothesis is that it has something to do with the initialization message "_Applying Migration for PF2e Drag Ruler Integration. Please be patient and do not close your game or shut down your server_." 

When the message appears in the server and is not removed, drag ruler appears to work. Here are two examples:
[Working on initialization of a new world](https://streamable.com/hjrmlu)
[Working on reload of the same world](https://webmshare.com/play/zOM6m)

However, it appears you can break this behavior by clicking the "x" next to the "_Applying Migration..._" message when it appears. When you do so, even uninstalling and reinstalling the modules (not just deselecting them in the module loader) still will not fix the module:
[Not working, even after complete reinstall of the modules](https://webmshare.com/play/9xM0y)

Is it possible that there is something in the affected game world that is saving a cache of the _pf2edragruler_ settings even when the module is uninstalled, and that is breaking the compatibility even after a reinstall?

**Comment by velara** [comment]
Only your first webm video is working for me. The others have a length of 0 seconds when i try and view them.

The migration does set a version number which would persist even after uninstall. However I can’t figure out how to replicate your bug. Clicking the x on those messages doesn’t trigger any change in behaviour for me. And to my understanding it shouldn’t trigger any change in behaviour. 

My best guess is that the code that is checking for version number is encountering a bug on your world which throws an exception and prevents the rest of the module from being loaded. Could you check the console for errors.

**Comment by pizza-wizard** [comment]
Apologies, the first video is hosted on a different platform than the other two, so that may be what's causing issues. I can see all of them in Chrome, if that helps.

I re-enabled only _drag ruler_ + _socketlib_ + _pf2edragruler_ and tried to move one of the actor tokens with the console visible. I've attached the error message to this comment.
![Screenshot 2021-06-06 131014](https://user-images.githubusercontent.com/83844868/120933587-c4a77600-c6c8-11eb-8ef8-b103f9a1e80e.png)

**Comment by velara** [comment]
I still have no idea about your initial issue. However regarding the error message it appears to be because scene movement switching is turned on without its dependency enhanced terrain layer. I’ve written a fix that will make that fail more elegantly. 

And made a slight tweak to the upgrade path that might help with your initial problem. I’m unsure, since I haven’t managed to reproduce that bug

**Comment by pizza-wizard** [comment]
Whatever the issue was, after updating to pf2edragruler 0.5.1, it appears to have fixed itself. Now everything is functioning as intended!

**Comment by velara** [comment]
I’m delighted it fixed it for you!
