### ISSUE TITLE
"Automatic Movement Switching" breaks Terrain Layer/Ruler when starting movement inside Terrain Area

### ISSUE THREAD

**Issue by InfamousSky** [velara/pf2edragruler#20]
![image](https://user-images.githubusercontent.com/88115652/127772176-fee1f207-b7b1-4ffa-b872-b9586aad509d.png)

When starting a movement inside a Terrain Area, Difficult Terrain stops being calculated and above error appears in console.
This only happens when the setting "Automatic Movement Switching" is enabled.

Tested in New World with:
Drag Ruler
Enhanced Terrain Layer
Pf2e Drag Ruler Integration
socketlib
Terrain Ruler

**Comment by velara** [comment]
Looks like an Enhanced Terrain Layer update got rid of one of the functions I was using. Should hopefully be an easy-ish fix. 

Today’s a travel day, but I’ll try and carve out sometime tomorrow to find a fix.
