### ISSUE TITLE
Ignore and reduce non-magical effects don't work correctly.

### ISSUE THREAD

**Issue by DoggieBert** [velara/pf2edragruler#21]
Both the ignore and reduce non-magical movement effects are ignoring all difficult terrain regardless of terrain movement cost or type.
This was tested with the following modules active.
![image](https://user-images.githubusercontent.com/53953028/128195563-67b7d30b-865b-4564-a9eb-c78ad0f7d900.png)

**Comment by velara** [comment]
I'm working on this. There was a typo introduced during some refactoring, which after I fixed, I discovered a change to ETL that makes is hard to ignore/reduce terrain with no-environment.

**Comment by velara** [comment]
And fixed
