### ISSUE TITLE
Doesn't work with metric system

### ISSUE THREAD

**Issue by mech-tools** [velara/pf2edragruler#3]
Hello,

When using metric system, a character can have decimals in movement speed. E.g 7.5 meters as movement speed.
I believe that your module is using parseInt functions. That won't work in this case.
Would you mind using parseFloat instead?

Thx.

**Comment by velara** [comment]
Ah, I’ve always preferred the 5ft to 2m conversation so I hadn’t even thought about fractional speeds. 

I’ll try subbing out the parseInt functions for parseFloat and make sure it doesn’t break anything. 

Assuming that works, I’ll put out a patch.

**Comment by mech-tools** [comment]
@velara wrote a PR for that https://github.com/velara/pf2edragruler/pull/4

**Comment by velara** [comment]
Thanks for writing the commit. I was putting it off until I had time to do some testing to make sure it wouldn't break anything as a side effect. I ran a quick set of tests on my development environment and the switch to ParseFloat doesn't seem to break anything unexpected. I'll accept your commit and update the package accordingly
