### ISSUE TITLE
Manifest URL points to old module or it is wrong

### ISSUE THREAD

**Issue by r-valyar** [velara/pf2edragruler#30]
The module cannot be updated, it seems the Manifest URL is wrong

![image](https://user-images.githubusercontent.com/63558984/155014391-284e9a55-caa2-4bc5-ab95-7b581e9e4dcd.png)

**Comment by velara** [comment]
Working on getting this resolved. Foundry seems to be treating the oldest version of modules as the latest version, which is affected a bunch of other modules as well.

**Comment by velara** [comment]
![image](https://user-images.githubusercontent.com/74130268/155027586-cb366709-a1b2-4076-9548-6a7e46028709.png)
Based on my testing this issue should be resolved now that the foundry staff have put out a fix. Please drop me a line if you run into further issues.
