### ISSUE TITLE
Foundry V10 Compartibility

### ISSUE THREAD

**Issue by medeiros961030** [velara/pf2edragruler#31]
Now that Drag Ruler has support for V10, are you planning to update this module to V10?

**Comment by velara** [comment]
Drag ruler does not yet have support for v10?

If you’re referring to the fork I’m considering it, but it makes prerequisites extremely difficult to handle appropriately.

**Comment by medeiros961030** [comment]
Sorry, I do not understand. The module "pf2e drag rule integration" made that every time someone walked, it changed the color based on the amount of actions, in addition to showing the distance that he walked in his turn, correct?

ME was informed that this module has not been updated to V10 because the "drag ruler" module has not been updated to V10 yet... but they have just updated the drag ruler to V10. I would like to know if you will update too

**Comment by velara** [comment]
https://foundryvtt.com/packages/drag-ruler

The listed Drag Ruler package was last updated 5 months ago. It has not been updated for v10 compatibility yet. 

Once it has been updated, I will be updating the module.

 I might try and sort out things with the fork 

https://github.com/Traumi/foundryvtt-drag-ruler

Which put together a temporary fix for drag ruler on v10. I’m told it works already, but just throws compatibility errors. But I’ll make no promises about supporting the fork.

**Comment by Ghilteras** [comment]
https://github.com/manuelVo/foundryvtt-drag-ruler/issues/229

v10 compatibility is coming

**Comment by JDCalvert** [comment]
Drag Ruler has now been officially updated with v10 compatibility.

**Comment by Rikshy** [comment]
from their changelog:

- Drag Ruler's API no longer supports the function `getCostForStep`. Instead, module authors are asked to use [Enhanced Terrain Layer's game system integration API](https://github.com/ironmonk88/enhanced-terrain-layer/blob/main/README.md#integrating-game-system-rules) to introduce game system specific terrain rules.

**Comment by velara** [comment]
I've got some questions/concerns about the new API that will take some time to get sorted out. 

My current plan is: I'm going to release a v10 compatible branch with no difficult terrain support later today so we have a nice error/warning free module for everyone to use. I'll re-add the functionality in a subsequent release once I've got things squared away with how I'm going to handle the new API.
