### ISSUE TITLE
Feature request: a way to hide measurements from players 

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [velara/pf2edragruler#36]
i was thinking that it would be good idea to have a button on the left hand side on the measurement tab to click so gms can hide their measurements from players. or a setting to hide gms measurements from players check box. to keep things as a suprise.

**Comment by velara** [comment]
![image](https://user-images.githubusercontent.com/74130268/222813123-dd281fb2-c2fe-40cc-9f39-6c8db25d9b2a.png)
This should be a setting in Drag Ruler. If it isn't working with the integration let me know and we can see about getting it fixed.

**Comment by ThingsCouldGetDicey** [comment]
i think this is fine.
