### ISSUE TITLE
Crash when setting waypoints with the wrong buttons

### ISSUE THREAD

**Issue by NikolasTzimoulis** [velara/pf2edragruler#39]
If you attempt to set waypoints with the following method:

1. Drag a token by holding the left mouse button.
2. Simultaneously release the left button and press right-click.
3. Continue dragging without pressing any buttons.
4. Press left-click to finish.

then foundry crashes with the following error:

```
Uncaught TypeError: Cannot read properties of null (reading 'clear')
[No packages detected]
    at z.clear (SmoothShader.ts:4)
    at TokenPF2e._refreshTarget (foundry.js:46327)
    at TokenLayerPF2e._animateTargets (foundry.js:37292)
    at t.emit (ticker.min.mjs:8)
    at e.update (ticker.min.mjs:8)
    at _tick (ticker.min.mjs:8)
```

Refreshing the page with F5 returns it to a working state. 

See also this video for reproduction steps:

https://user-images.githubusercontent.com/380852/214138664-b6a63f1e-2270-4e5e-9b21-d925e6e83691.mp4

If you don't finish setting waypoints at that time but instead attempt to create new ones, this unexpected and possibly related behaviour occurs:

https://user-images.githubusercontent.com/380852/214138843-e4492af8-732b-4c65-84fa-8f6bcb906436.mp4

Based on limited testing, the crash only occurs in pf2e and not the dnd5e system with the main drag ruler module. However the weird behaviour in the second video occurs in both.

**Comment by velara** [comment]
I set down to try and replicate this, and I've been successful only at replicating the second set of behaviour, I have yet to replicate the crash.

**Comment by NikolasTzimoulis** [comment]
I just tested in an empty world, slowly adding modules one by one. It seems like the bug only occurs when [TouchVTT](https://github.com/Oromis/touch-vtt) is enabled, so that one is the culprit. 

Anyway, it doesn't matter much to be honest.
