### ISSUE TITLE
PF2E Drag Ruler Integration using wrong manifest url and downloading old V9 version through Foundry

### ISSUE THREAD

**Issue by TombstoneTT** [velara/pf2edragruler#41]
As said in the title. I was doing some reinstalling and know there's a version on v10, but for some reason, it's installing the old version.
![image](https://user-images.githubusercontent.com/100088774/215340708-ae5e7b4b-e738-4d61-b800-e34445801f5a.png)

**Comment by velara** [comment]
Something changed in the way foundry is handling finding the most up to date version of a module. I'm just waiting it out and hoping they fix it.

**Comment by TombstoneTT** [comment]
Anyway to force it back manually or nada?

**Comment by velara** [comment]
You could try reinstalling from the manifest directly. Either: https://raw.githubusercontent.com/League-of-Foundry-Developers/pf2edragruler/main/module.json which will ensure everything keeps working in terms of update paths, or https://raw.githubusercontent.com/League-of-Foundry-Developers/pf2edragruler/v2.1.5/module.json which will likely require you reinstall once all this is fixed if you want future updates.

**Comment by velara** [comment]
As a more general update, 
![image](https://user-images.githubusercontent.com/74130268/215350250-3c553367-6892-47fc-b009-ecb43005ace7.png)

Should hopefully be fixed by tomorrow.

**Comment by TombstoneTT** [comment]
Thanks! The second URL worked and I'll make sure to keep it in mind to reinstall once this is hopefully fixed tomorrow.

**Comment by velara** [comment]
Seems to be fixed now
