### ISSUE TITLE
feature request: being able to measure from the outline of a token

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [velara/pf2edragruler#46]
something that i cant do with this mod is being able to measure from the corner or outline of a token because it snaps to the center of a token. is there a hotkey that i can use to decouple that to the outline of a token. 

the reason being is that when you are trying to measure cover or anything like that you need to have line of sight from the edge of a token to the target to see it. and to be able to target it you need to be able to see it from the center of your token.

**Comment by velara** [comment]
This would be better made as a request to Drag Ruler. I don't actually set the start point for the measurement in this module.
