### ISSUE TITLE
Module localization.

### ISSUE THREAD

**Issue by DoctorDankovsky** [velara/pf2edragruler#48]
Good day. As a translator, I feel sad without localization files in the modules I use. If you don't mind, I made an initiative in the attached archive. I must say right away that I am not a programmer and could mess something up, if you decide to use it, please check before that.
[pf2e-dragruler.zip](https://github.com/League-of-Foundry-Developers/pf2edragruler/files/11009872/pf2e-dragruler.zip)

**Comment by velara** [comment]
I'll give a whirl, and hopefully include it next release.

**Comment by velara** [comment]
I failed to put out another v10 release, before the system updated to v11. But the localization, for the features that remained was incorporated into the v11 release.
