### ISSUE TITLE
Draw Shape Error when applying an effect to token 

### ISSUE THREAD

**Issue by velara** [velara/pf2edragruler#9]
Graphics.ts:896 Uncaught (in promise) TypeError: Cannot read property 'drawShape' of null
    at r.drawShape (Graphics.ts:896)
    at r.drawRoundedRect (Graphics.ts:815)
    at Token._drawEffect (foundry.js:44640)
    at async Promise.all (index 0)
    at async Token.drawEffects (foundry.js:44599)

Appears to be linked to Foundry's handling of webp files.

**Comment by velara** [comment]
Far as I can tell besides being noisy, this error doesn't appear to actually effect anything.

**Comment by JamzTheMan** [comment]
Along with the error I'm also getting double icons: 
![image](https://user-images.githubusercontent.com/8051654/116303969-b2e8bf80-a767-11eb-995f-ffa7745561ea.png)

**Comment by velara** [comment]
Well that's. Odd. 

The good news is it the afore mentioned error with drawShape appears to have been fixed in the PF2e master branch, thanks to a recent merge request. So it should go away with the next system release. 

As far as the double icons are concerned. It looks to me like its trying to do both vertical and horizontal stacking of the images. I've not be successful at reproducing this on my end. However, going through my test worlds I did notice duplication of all my effect icons in the world with CUB enabled. So that could potentially be a root cause. (If you do have CUB enabled you should be able to remove the duplicates using the token hud, condition menu. )

On the other hand if you don't have CUB installed my first suggestion would be to try removing the effects in question, if there no effect icons left on the token then reapply fresh from the compendium to see if the error persists. 

If you're still getting the error at that point, if you don't mind, you could send me an export of the actor in question and I'll take a look to see if I can determine the root cause.

**Comment by JamzTheMan** [comment]
OK, so yep, the double icons was a different module. It happens with any other "effect" that adds an icon to the token and it's from
Illandrils Token Hud Scaler.  Turning that mod off fixed the issue.

![image](https://user-images.githubusercontent.com/8051654/116445694-c81f2600-a81b-11eb-979a-81fe18133afb.png)

**Comment by velara** [comment]
Thanks for following up. I'm glad you found the root cause :D

**Comment by velara** [comment]
Fixed in latest PF2e system hotfix.
